export const PLANS = {
  free: {
    websites: 1,
    scanFrequency: "once",
    maxConcurrentScans: 1,
    rateLimitPerHour: 3,
    continuousMonitoring: false,
    detailedReports: false,
    changeAlerts: false,
    auditTrail: false,
    suggestions: false,
    aiAssistant: false,
    aiMonthlyRequests: 0,
    price: 0,
    stripePriceId: null,
  },

  starter: {
    websites: 1,
    scanFrequency: "weekly",
    maxConcurrentScans: 2,
    rateLimitPerHour: 20,
    continuousMonitoring: false,
    detailedReports: false,
    changeAlerts: false,
    auditTrail: false,
    suggestions: false,
    aiAssistant: false,
    aiMonthlyRequests: 0,
    price: 29,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_STARTER,
  },

  business: {
    websites: 10,
    scanFrequency: "continuous",
    maxConcurrentScans: 5,
    rateLimitPerHour: 100,
    continuousMonitoring: true,
    detailedReports: true,
    changeAlerts: true,
    auditTrail: true,
    suggestions: true,
    aiAssistant: true,
    aiMonthlyRequests: 5,
    price: 79,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_BUSINESS,
  },

  agency: {
    websites: Infinity,
    scanFrequency: "continuous",
    maxConcurrentScans: 10,
    rateLimitPerHour: 500,
    continuousMonitoring: true,
    detailedReports: true,
    changeAlerts: true,
    auditTrail: true,
    suggestions: true,
    aiAssistant: true,
    whiteLabel: true,
    centralDashboard: true,
    aiMonthlyRequests: 500,
    price: 199,
    stripePriceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_AGENCY,
  },
} as const;

export type Plan = keyof typeof PLANS;
